name: check
on:
  schedule:
    - cron: 10 14 * * *
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - shell: bash
      env:
        API_URL: ${{ secrets.API_URL }}
        ARGS: ${{ secrets.args }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        ./check $ARGS
        

