name: check
on:
  schedule:
    - cron: 10 4 * * *
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        GIST_URL: ${{ secrets.GIST_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_NUMBER: ${{ secrets.DB_NUMBER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
        WECHAT_OPENKEY: ${{ secrets.WECHAT_OPENKEY }}
        WECHAT_UNIONID: ${{ secrets.WECHAT_UNIONID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -sL "$GIST_URL" | bash 

